#ifndef GATE_CONSTANTS_H
#define GATE_CONSTANTS_H

#define NAND_DELAY 1
#define NOT_DELAY 1
#define AND_DELAY 2
#define OR_DELAY 2
#define NOR_DELAY 2
#define XOR_DELAY 3
#define FLIP_FLOP_DELAY (2 + 4*NOT_DELAY)


#define NOT_TRANSISTORS 2
#define NAND_TRANSISTORS 4
#define NOR_TRANSISTORS 4
#define AND_TRANSISTORS 6
#define OR_TRANSISTORS 6
#define XOR_TRANSISTORS 8
#define TRANSMISSION_GATE_TRANSISTORS 2
#define FLIP_FLOP_TRANSISTORS (4*TRANSMISSION_GATE_TRANSISTORS + 5*NOT_TRANSISTORS) 

#endif
